version: "3"
services:
  ebap:
    image: ghcr.io/yaegashi/easy-basic-auth-proxy
    build: .
    ports:
      - "8080:80"
    environment:
      EBAP_LISTEN: :80
      EBAP_TARGET_URL: http://whoami:8080
      EBAP_ACCOUNTS_DIR: /data/ebap/accounts
      EBAP_DEVELOPMENT: true
      EBAP_SESSION_KEY: 0123456789abcdef0123456789abcdef
    volumes:
      - ./data/ebap:/data/ebap
  whoami:
    image: traefik/whoami
    command:
      - --port=8080
