version: "3"
services:
  proxy:
    build: .
    ports:
      - "8080:8080"
    environment:
      EABP_UPSTREAM_URI: http://bagetter:8080
      EABP_ACCOUNTS_DIR: /accounts
    volumes:
      - ./data/sccounts:/accounts
  bagetter:
    image: bagetter/bagetter
