version: "3"
services:
  proxy:
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_UPSTREAM: http://bagetter:8080
      APP_STORE_PATH: /store
    volumes:
      - ./data/store:/store
  bagetter:
    image: bagetter/bagetter
